### ISSUE TITLE
Disabling the username/profile pic, while leaving the password box enable, can force Windows in a login screen loop

### ISSUE THREAD

**Issue by KaleidonKep99** [PFCKrutonium/Windows-10-Login-Background-Changer#125]
I enabled the option to hide both username and profile pic, while leaving the password box enabled, and that corrupted something on Windows, causing it to try showing the login screen, while failing.

**Comment by tetra-fox** [comment]
Those switches do nothing to the logon screen. Those are just for the preview purposes. That's why they are listed under the "APPLICATION SETTINGS" group. The reason you're in this loop is just the fact that you changed the image. It's a common issue. [Read the wiki for more information.](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can%27t-Login/)

**Comment by KaleidonKep99** [comment]
Well, I didn't.
I only changed the style of the login screen, the background is the same as before. (Windows logo with strange light shapes)

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
