### ISSUE TITLE
Login screen is broken

### ISSUE THREAD

**Issue by insertc0in** [PFCKrutonium/Windows-10-Login-Background-Changer#135]
Yeah, didn't work for me. I'm using Win 10 Pro x64 pt_PT
Screen just flickers and can't login anymore, just restored the backup.
Not sure if important but the original pri file is around 2MB while the tool changed to 11MB, although the image I used was just 1.5MB. Also, I hope this can help troubleshoot: http://s000.tinyupload.com/index.php?file_id=15745156601115618782

**Comment by tetra-fox** [comment]
[you've been added to the issue hall of fame](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki/Can't-Login)

also, the reason the file changed to 11mb even though your image was 1.5mb was because in the pri file, there are multiple image sizes, so we have to make multiple copies of your image in the file.

**Comment by darth62969** [comment]
do you really need to be that snarky about it?

**Comment by insertc0in** [comment]
@darth62969 don't be childish

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
