### ISSUE TITLE
Add bak file to auto copy to Windows.UI.Logon

### ISSUE THREAD

**Issue by cololi** [PFCKrutonium/Windows-10-Login-Background-Changer#233]
many people forgot add file can't login system

**Comment by Krutonium** [comment]
Can you elaborate?

**Comment by darth62969** [comment]
i think he is talking about the people that don't have the .bak file. so if you can't back it just copy one over.

we can't do this because of licensing. i don't think MS would care but legally we still can't do it. the best option it to get the PRI from another computer and use that to restore the settings.

this has already been addressed but we still need a solution.

**Comment by emmatyping** [comment]
assuming darth62969 is right, we cannot do so, if darth62969 is wrong, leave a comment explaining more.
