### ISSUE TITLE
Working with version 1511 build 10586.17?

### ISSUE THREAD

**Issue by arieljannai** [PFCKrutonium/Windows-10-Login-Background-Changer#273]
Question:
I've just got this update (build 10586.17) yesterday, and I can see that somethings in the UI has been changed (the pri file has been replaced by a new one). Is it tested with that version?

Thanks

**Comment by darth62969** [comment]
yes the latest dev build it has been, however the latest release, i am not sure on, not to mention it still has a few bugs that are not present in the dev build. so you have 2 options, build the dev release and run it, or you can use the last release which should work as nothing has changed dramatically since it's release. if you run into any issues let us know.
