### ISSUE TITLE
Login issue cause and temporary fix

### ISSUE THREAD

**Issue by GbrFrn** [PFCKrutonium/Windows-10-Login-Background-Changer#276]
#edited since that wasn't really what happened.

**Comment by emmatyping** [comment]
Well, our program _shouldn't_ do that. I am guessing Windows is mis-identifying your keyboard as another type. What keyboard layout are you using?

**Comment by GabrFerm** [comment]
nope, i'm using pt-br abnt2 and windows is configurated correctly, just downloaded avast and ran a quick scan and the problem was solved, but no virus was appointed by the avast somehow... I suggest that you run a search for unwanted code on your application mate, someone may have injected some kind of virus, or something like that onto it. Tks for the support, gl

**Comment by Krutonium** [comment]
I've been watching this repo since the day I created it and reviewed the code as it arrived - there is no code in this that could nor would change your keyboard settings. May I suggest http://www.thewindowsclub.com/reset-keyboard-settings-default-windows
