### ISSUE TITLE
Hiding user info and glyphs only shows it on the program

### ISSUE THREAD

**Issue by foxt** [PFCKrutonium/Windows-10-Login-Background-Changer#290]
Build 10240 as admin.
Hi, Deselecting the "Show Userinfo" only hides it on the program not on the lock. This is possible because I've seen another program do it. Might of been this one.

**Comment by Toyz** [comment]
What other programs cause that info is system dependent in the PRI and no. Way to. Edit the pris internal xmal 
On Mar 2, 2016 10:28 AM, LMGN notifications@github.com wrote:Build 10240 as admin.
Hi, Deselecting the "Show Userinfo" only hides it on the program not on the lock. This is possible because I've seen another program do it. Might of been this one.

**Comment by Theletha** [comment]
so it's not possible? why isn't that option labeled as it won't affect the lockscreen kinda looks like it should take it away in the lockscreen...

**Comment by emmatyping** [comment]
It is not. The file we modify is an undocumented format and MS severely restricts knowledge of the format. If we wanted to edit more, it would take a large investment of time to reverse engineer the format.

**Comment by Theletha** [comment]
i managed to remove the picture at least!

http://imgur.com/aES064T

**Comment by emmatyping** [comment]
Mind sharing how you went about that? I took an image and modified it to fit the background, but that is not a great solution...

**Comment by foxt** [comment]
@ethanhs Deleting all the files in `C:\Users\Public\AccountPictures\`
