### ISSUE TITLE
Black Lock Screen After KB3081424 Update

### ISSUE THREAD

**Issue by Spidermain50** [PFCKrutonium/Windows-10-Login-Background-Changer#98]
The lock screen that shows the time and prompts for Ctrl+Alt+Delete is now completely black after the latest Windows Update. I can still unlock it with Ctrl+Alt+Delete and it takes me to the password screen like normal. I tried restoring defaults the background changer, but it does not fix the issue.

**Comment by Toyz** [comment]
The lock screen is controlled by your system settings the logon background is controlled by ares, look at your lock screen settings in personalization

**Comment by tetra-fox** [comment]
[please read the wiki](https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/wiki)

**Comment by cx99** [comment]
From what I can tell the wiki and lock screen settings don't really apply here. You don't need a pre-boot method of undoing this because you can still log in. It's not just a black background or something controlled by system preferences, it's a fully black screen with just a cursor showing and as Spidermain50 pointed out, you can get past it with ctrl+alt+del

**Comment by darth62969** [comment]
Fixed in latest update, open a new issue if it does not work.

https://github.com/PFCKrutonium/Windows-10-Login-Background-Changer/releases/tag/1.2.0.0
